config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#top'


  post 'books' => 'books#create'

  get 'books' => 'books#index'

  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end


  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice]='Book was successfully created.'
      redirect_to book_path(@book)
    else
      @books = Book.all.order("id ASC")
      render :index
    end
  end

  def index
  @book = Book.new
    @books = Book.all.order("id ASC")
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]='Book was successfully updated.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice]='Book was successfully destroyed.'
    redirect_to books_path
  end

# ストロングパラメータ
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p class="flash_message"><%= flash[:notice] %></p>

<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<!-- ここからエラーメッセージ -->
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- ここまでエラーメッセージ -->

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <p><%= f.submit 'Update Book' %></p>
  <span><%= link_to 'Show', book_path(@book) %></span>
  <span><%= link_to 'Back',books_path %></span>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
<p class="flash_message"><%= flash[:notice] %></p>
<% end %>

<h1>Books</h1>
<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
</thead>
<tbody>
<% @books.each do |book| %>
  <tr>
  	<td width = "300"><%= book.title %></td>
    <td width = "600"><%= book.body %></td>
    <td><%= link_to 'Show', book_path(book.id) %></td>
    <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy', destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
<% end %>
</tbody>
</table>


<!-- 新規投稿画面 -->
<div class="newbook">
<h2 class="newbook_title">New book</h2>
<div class ="form"><%= form_for(@book) do |f| %>
  <!-- ここからエラーメッセージ -->
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- ここまでエラーメッセージ -->
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <p><%= f.submit 'Create Book' %></p>
</div>
<% end %>
</div>

app/views/books/new.html.erb
<!-- 新規投稿画面 -->
<h2>New book</h2>
<%= form_for(@book) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p class="flash_message"><%= flash[:notice] %></p>
<% end %>
<p><strong>Title:</strong><%= @book.title %></p>
<p><strong>Body:</strong><%= @book.body %></p>
<span><%= link_to 'Edit', edit_book_path(@book) %></span>
<span><%= link_to 'Back', books_path %></span>

app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
<p><strong>Bookers</strong>では、さまざまな書類に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to 'start',books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>